sudo: false

language: c

addons:
  apt:
    packages:
    - luarocks

env:
  global:
  - secure: "iq2FEUujtcVaIiLBq2fRKNGgBN9uFRbrdFwj22ApEiDZrWpLBUZ7n83yM+SpgMry+x/HktnOWO5AdYy0iINiocIe2Uk2u8i6uwB9uwzf1Lc2YpEjM1nBpgw4/JpeqjZ0cTGsD1AjnFeyzr0NXouBy6EAwLpfMc0sq7gHCgYUENNS2ZPSVE4evM7PYuLunmJ+BoqwKa5r6N5G6ky+oTGEphYB32jbapPG9ewU25PB8qoPbWxo6Xis3rsmN4DA2dOFRNuFpgeJXFeYVm/0bUbZpJ+xMtlPokHWYNuVLmaqtRdmR3AvQelMBM0GJQEUcKTTZiAOcdvgboUDlCgK0lnXZPjXiXFpb0j04DzmFbcnZfLRucdqbmnxZM+eBDHJa7O9IxWdeV6ALkH4blYaxNfwuOj+C384WAs/g5ExD0e6QE0Sccbb8fntqAlGOGtv0mY9XhPDo7hygdvs95HnvRZL3wuh4vwY/dvaC4PdMMvy2WwQvkhlUmvdBKKm+VVnhQ1IcwrZCvfGRLvdf8SmpcdzW3+AJil95lu42Nps6XFH8bRKAQClffa5ZY5V4sTsV3776TDhqIGMvGve9c/ODei58eFW4h1o6NsQHns1Vk8Fa9d11Sql77YJUL9hlGT04BJR2q3U9XjwHBRRVFNOqopSVUiKRb7J6waV/9IfmXrOudk="
  - secure: "ZhT8ecO7W5wuwfEn5ciLDEfl+YE7wS+2/Ela1GTJI6PQZTzAIWBU60nK+Yct1fCUWlnAsVTDSKuuc/KHcASIJiuAqAgC560s21ysCqdxfsPNDc0DblZxa/+1q7EAziCI0cyOR7Hm9QtZSdFbU+hfTKmiaJNE6KuchxIn46GWirLZo4nBHFMefBh7bmjJkARfx28g3wBoV3WfDZL0GVn9WINJdycZwCAMSrYTdH/SGL16iKhLpgyduTrURwEIa9tmrmKPFIXfEfwcIaaXKy0I32DvFC2Hm8uudZSBSvg+LjuaWOlfT4lIUaYwwx9Xp3ncuhXYGPSo7MIM5RftkTufM6+5ofGpmEcTO7DR2nLPKqDw9cVxiqI31b65So6TrCjnvQKk/eMVZve7Uzy0v6dE5ngtIb0RljVXCRtBmxCHxU/85PQufpwUA3yEISuBge9Ww+rEXThKjnWEsUy7KDNCsORJPZ+E1oU/09Zp1dBqvy40BtfKx9dyFHwwpbRRlG3C2MjbDcXZEsXFC2FspyVmARorgt+0I5fOd401PW7+7hpkR387HNsB9sBgMwzwgm+ydVK4VD5XJy/McqrCR6J0Up02q1Bfmvg1awDhGoBWf+QEbIRf8K9sFR2+b5kkKEqtCfAF27P4KyHX72gvzlvNA9cEhH++CjRkf2fV8r3659k="
  - secure: "mdZdo6KGgCjoeIANaggH44vAUVnfl2+pKGRpOdbQcVr+z8aw9XjWs9aGWfXLgWMLdNyL9zcgNDV+XgC/DcyWF3fRA6zSU6wQVz3RZJn5mQXhiR06jfCxgSKKKiygBcXN2xxZG7Mknc7Mm52H/PKB/FbbitbYafj0S8dQDPn3bSFumTO7LTAd2YqQjGgKoRUnG5RxG2gXFr2nGPePnKldatcSvKnH6QLMv7jrhsyGOzDQWxa+yXoC0Ihrer+C6y113u04e+p4zr6vjhHUlDjoJY4wWKuU5LEni45oZ5can2jzErosbSzwaPGGo06l1GyQo0kbspRPTYEZnDlT03TDvx/stAM3CP2yhyG3i/gffdB4PNBx6vX4GkCdF9tz1nkhg8P3vOEajpJ8Iq6fvt29u+ZtcQ7t41bTBh1loQsvTy4O8/axv2nWPSVJbOGn4qPniTD75e0Mmkr1F+J5WMadB7mLVE1C3XKq/VmTqk8Td8hM7ztugs/IR46UiOH6cdJaSJVEdTi4yEzYu8l7mCkk36aoi3soxCP4pbcKAB69+RYX+VVARHJC0bBZgxI+WF3fhVYPudqLMDlyKnH7k+iXWWx+XR3dzHyHvniH/v2TDTvjy/Fj41g89ANj+d0X8M1/OOZnnV2+gH6JW7wCOP4WN0ubx82purP+EdFJOUoAqYY="

before_install: luarocks install --local luacheck

before_script: /home/travis/.luarocks/bin/luacheck . --no-color -qo "011"
script: curl -s https://raw.githubusercontent.com/BigWigsMods/packager/master/release.sh | bash

notifications:
  email:
    on_success: never
    on_failure: always
